name: 💖 PR Polish

on:
  pull_request:
    types: [opened, edited]
    branches:
      - '**'

jobs:
  pretty-prs:
    name: 💅 Yassify PR
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Yassify PR name
        uses: ./.github/actions/pretty-pr
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
